In [7]:
import pandas as pd

In [11]:
df=pd.read_csv(r"E:\python\project 2\cybersecurity_auth_risk_analytics.csv")

In [12]:
df.head()

,Event_ID,Timestamp,User_ID,Username,IP_Address,Device_Type,Operating_System,Browser,Location,Country,Authentication_Method,Login_Status,Failure_Reason,Account_Status,Login_Hour,Is_Night_Login,Session_ID
0,EVT_100000,2026-08-01 00:01:01,USR_1020,user_1020,45.23.157.20,Laptop,macOS,Firefox,Berlin,Germany,Biometric,Success,NaN,Active,0,Yes,ABE73A9E-0752-48BD
1,EVT_100001,2026-08-01 00:01:28,USR_1120,user_1120,10.0.0.81,Desktop,macOS,Edge,Toronto,Canada,SSO,Success,NaN,Active,0,Yes,16155216-B08E-42B4
2,EVT_100002,2026-08-01 00:01:44,USR_1120,user_1120,10.0.0.81,Desktop,macOS,Firefox,Toronto,Canada,Biometric,Success,NaN,Active,0,Yes,92F922BE-3236-4704
3,EVT_100003,2026-08-01 00:02:31,USR_1105,user_1105,10.0.0.223,Mobile,iOS,Safari,Singapore,Singapore,Password,Success,NaN,Active,0,Yes,BF31119C-4607-4E4E
4,EVT_100004,2026-08-01 00:03:17,USR_1029,user_1029,10.0.0.239,Tablet,Android,Safari,Dubai,UAE,SSO,Failed,Account Locked,Locked,0,Yes,657B6679-6315-4B60

In [13]:
df.shape

(20015, 17)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20015 entries, 0 to 20014
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Event_ID               20015 non-null  str
 1   Timestamp              20015 non-null  str
 2   User_ID                20015 non-null  str
 3   Username               20015 non-null  str
 4   IP_Address             19990 non-null  str
 5   Device_Type            20015 non-null  str
 6   Operating_System       20015 non-null  str
 7   Browser                20015 non-null  str
 8   Location               19990 non-null  str
 9   Country                20015 non-null  str
 10  Authentication_Method  20015 non-null  str
 11  Login_Status           20015 non-null  str
 12  Failure_Reason         2401 non-null   str
 13  Account_Status         20015 non-null  str
 14  Login_Hour             20015 non-null  int64
 15  Is_Night_Login         20015 non-null  str
 16  Session_ID             20015 non-null  str
dtypes: int64(1), str(16)
memory usage: 5.0 MB

In [15]:
df.isnull().sum()

Event_ID                     0
Timestamp                    0
User_ID                      0
Username                     0
IP_Address                  25
Device_Type                  0
Operating_System             0
Browser                      0
Location                    25
Country                      0
Authentication_Method        0
Login_Status                 0
Failure_Reason           17614
Account_Status               0
Login_Hour                   0
Is_Night_Login               0
Session_ID                   0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(15)

In [17]:
df=df.drop_duplicates()

In [18]:
df.shape

(20000, 17)

In [19]:
print(df["Login_Status"].value_counts())
print("\n-------------------\n")

print(df["Device_Type"].value_counts())
print("\n-------------------\n")

print(df["Authentication_Method"].value_counts())
print("\n-------------------\n")

print(df["Is_Night_Login"].value_counts())

Login_Status
Success    17577
Failed      2393
success       25
failed         5
Name: count, dtype: int64

-------------------

Device_Type
Desktop    5132
Mobile     5112
Laptop     5012
Tablet     4714
MOBILE        8
TABLET        8
DESKTOP       8
LAPTOP        6
Name: count, dtype: int64

-------------------

Authentication_Method
Password     5128
MFA          5035
SSO          4969
Biometric    4868
Name: count, dtype: int64

-------------------

Is_Night_Login
No     14849
Yes     5151
Name: count, dtype: int64

In [20]:
# Standardize Login_Status
df["Login_Status"] = df["Login_Status"].str.strip().str.title()

# Standardize Device_Type
df["Device_Type"] = df["Device_Type"].str.strip().str.title()

In [21]:
print(df["Login_Status"].value_counts())
print("\n-------------------\n")

print(df["Device_Type"].value_counts())
print("\n-------------------\n")

Login_Status
Success    17602
Failed      2398
Name: count, dtype: int64

-------------------

Device_Type
Desktop    5140
Mobile     5120
Laptop     5018
Tablet     4722
Name: count, dtype: int64

-------------------

In [22]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

df["Timestamp"].dtype

dtype('<M8[us]')

In [23]:
df["IP_Address"] = df["IP_Address"].fillna("Unknown")
df["Location"] = df["Location"].fillna("Unknown")

In [24]:
df[["IP_Address", "Location"]].isnull().sum()

IP_Address    0
Location      0
dtype: int64

In [25]:
pd.crosstab(df["Login_Status"], df["Failure_Reason"].isnull())
# This will tell us whether missing Failure_Reason values mainly belong to successful logins.

Failure_Reason  False  True
Login_Status
Failed           2398      0
Success             0  17602

In [26]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nDataset Shape:")
print(df.shape)

Missing Values:
Event_ID                     0
Timestamp                    0
User_ID                      0
Username                     0
IP_Address                   0
Device_Type                  0
Operating_System             0
Browser                      0
Location                     0
Country                      0
Authentication_Method        0
Login_Status                 0
Failure_Reason           17602
Account_Status               0
Login_Hour                   0
Is_Night_Login               0
Session_ID                   0
dtype: int64

Duplicate Rows:
0

Dataset Shape:
(20000, 17)

In [27]:
df.to_csv(r"E:\python\project 2\cybersecurity_auth_risk_analytics.csv", index=False)

In [28]:
# Count failed login attempts for each user
failed_by_user = (
    df[df["Login_Status"] == "Failed"]
    .groupby("User_ID")
    .size()
)

In [29]:
df["User_Failed_Login_Count"] = df["User_ID"].map(failed_by_user).fillna(0)

In [30]:
df

,Event_ID,Timestamp,User_ID,Username,IP_Address,Device_Type,Operating_System,Browser,Location,Country,Authentication_Method,Login_Status,Failure_Reason,Account_Status,Login_Hour,Is_Night_Login,Session_ID,User_Failed_Login_Count
0,EVT_100000,2026-08-01 00:01:01,USR_1020,user_1020,45.23.157.20,Laptop,macOS,Firefox,Berlin,Germany,Biometric,Success,NaN,Active,0,Yes,ABE73A9E-0752-48BD,9
1,EVT_100001,2026-08-01 00:01:28,USR_1120,user_1120,10.0.0.81,Desktop,macOS,Edge,Toronto,Canada,SSO,Success,NaN,Active,0,Yes,16155216-B08E-42B4,20
2,EVT_100002,2026-08-01 00:01:44,USR_1120,user_1120,10.0.0.81,Desktop,macOS,Firefox,Toronto,Canada,Biometric,Success,NaN,Active,0,Yes,92F922BE-3236-4704,20
3,EVT_100003,2026-08-01 00:02:31,USR_1105,user_1105,10.0.0.223,Mobile,iOS,Safari,Singapore,Singapore,Password,Success,NaN,Active,0,Yes,BF31119C-4607-4E4E,8
4,EVT_100004,2026-08-01 00:03:17,USR_1029,user_1029,10.0.0.239,Tablet,Android,Safari,Dubai,UAE,SSO,Failed,Account Locked,Locked,0,Yes,657B6679-6315-4B60,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,EVT_119995,2026-08-15 12:03:30,USR_1152,user_1152,10.0.0.215,Tablet,iOS,Chrome,Paris,France,SSO,Failed,MFA Failed,Active,12,No,6957A8CF-184D-405E,11
19996,EVT_119996,2026-08-15 12:04:40,USR_1000,user_1000,192.168.1.16,Mobile,iOS,Edge,London,UK,Password,Success,NaN,Active,12,No,23D7B10E-5389-40BD,11
19997,EVT_119997,2026-08-15 12:05:29,USR_1054,user_1054,192.168.1.15,Laptop,macOS,Safari,Sydney,Australia,SSO,Success,NaN,Active,12,No,756C4401-EA21-4D3A,9
19998,EVT_119998,2026-08-15 12:06:30,USR_1183,user_1183,192.168.1.224,Laptop,macOS,Firefox,Mumbai,India,Password,Success,NaN,Active,12,No,AC2C3F82-CC30-44F3,12
19999,EVT_119999,2026-08-15 12:07:06,USR_1162,user_1162,192.168.1.190,Desktop,Windows,Edge,Tokyo,Japan,MFA,Success,NaN,Active,12,No,A0656F56-1A4F-4D48,10

In [31]:
df["User_Failed_Login_Count"].describe()

count    20000.000000
mean         9.711400
std          2.842888
min          4.000000
25%          8.000000
50%         10.000000
75%         11.000000
max         20.000000
Name: User_Failed_Login_Count, dtype: float64

In [32]:
failed_by_ip = (
    df[df["Login_Status"] == "Failed"]
    .groupby("IP_Address")
    .size()
)
df["IP_Failed_Login_Count"] = (
    df["IP_Address"].map(failed_by_ip).fillna(0)
)
df["IP_Failed_Login_Count"].describe()

count    20000.000000
mean         9.443650
std         15.484286
min          0.000000
25%          4.000000
50%          7.000000
75%         10.000000
max        113.000000
Name: IP_Failed_Login_Count, dtype: float64

In [33]:
users_per_ip = df.groupby("IP_Address")["User_ID"].nunique()
df["Users_Per_IP"] = df["IP_Address"].map(users_per_ip)
df["Users_Per_IP"].describe()

count    20000.00000
mean         4.67095
std         17.53601
min          1.00000
25%          1.00000
50%          2.00000
75%          3.00000
max        125.00000
Name: Users_Per_IP, dtype: float64

In [34]:
locations_per_user = df.groupby("User_ID")["Location"].nunique()    
df["Locations_Per_User"] = df["User_ID"].map(locations_per_user)       
df["Locations_Per_User"].describe()

count    20000.000000
mean         2.129350
std          0.982836
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          5.000000
Name: Locations_Per_User, dtype: float64

In [35]:
df["Risk_Score"] = 0

# Rule 1: Failed login
df.loc[df["Login_Status"] == "Failed", "Risk_Score"] += 30

# Rule 2: Night login
df.loc[df["Is_Night_Login"] == "Yes", "Risk_Score"] += 10

# Rule 3: Repeated failed logins by user
df.loc[df["User_Failed_Login_Count"] >= 12, "Risk_Score"] += 15

# Rule 4: High failed login activity from IP
df.loc[df["IP_Failed_Login_Count"] >= 15, "Risk_Score"] += 20

# Rule 5: IP used by many users
df.loc[df["Users_Per_IP"] >= 5, "Risk_Score"] += 10

# Rule 6: User logging in from multiple locations
df.loc[df["Locations_Per_User"] >= 4, "Risk_Score"] += 10

# Rule 7: Locked account
df.loc[df["Account_Status"] == "Locked", "Risk_Score"] += 15





df["Risk_Score"].describe()     
df["Risk_Score"].value_counts().sort_index()

Risk_Score
0      9178
10     3434
15     2393
20      605
25     1048
30      736
35      440
40      547
45      387
50       66
55      532
60      179
65       81
70      172
75      111
80       21
85       41
90       23
95        1
100       4
110       1
Name: count, dtype: int64

In [36]:
def classify_risk(score):
    if score <= 20:
        return "Low"
    elif score <= 45:
        return "Medium"
    elif score <= 65:
        return "High"
    else:
        return "Critical"
df["Risk_Level"] = df["Risk_Score"].apply(classify_risk)
df["Risk_Level"].value_counts()

Risk_Level
Low         15610
Medium       3158
High          858
Critical      374
Name: count, dtype: int64

In [37]:
df[df["Risk_Level"] == "Critical"][
    [
        "Event_ID",
        "User_ID",
        "IP_Address",
        "Location",
        "Login_Status",
        "Is_Night_Login",
        "User_Failed_Login_Count",
        "IP_Failed_Login_Count",
        "Users_Per_IP",
        "Locations_Per_User",
        "Account_Status",
        "Risk_Score",
        "Risk_Level"
    ]
].head(10)

,Event_ID,User_ID,IP_Address,Location,Login_Status,Is_Night_Login,User_Failed_Login_Count,IP_Failed_Login_Count,Users_Per_IP,Locations_Per_User,Account_Status,Risk_Score,Risk_Level
4,EVT_100004,USR_1029,10.0.0.239,Dubai,Failed,Yes,12,11.0,2,3,Locked,70,Critical
40,EVT_100040,USR_1169,198.51.100.42,Paris,Failed,Yes,9,105.0,116,3,Active,70,Critical
52,EVT_100052,USR_1109,192.168.1.180,Mumbai,Failed,Yes,12,5.0,1,2,Locked,70,Critical
57,EVT_100057,USR_1193,192.168.1.146,Sydney,Failed,Yes,12,5.0,1,4,Locked,80,Critical
61,EVT_100061,USR_1220,10.0.0.59,London,Failed,Yes,12,18.0,3,1,Active,75,Critical
80,EVT_100080,USR_1213,203.0.113.115,Paris,Failed,Yes,11,113.0,125,3,Active,70,Critical
81,EVT_100081,USR_1247,192.168.1.201,Dubai,Failed,Yes,13,9.0,3,2,Locked,70,Critical
104,EVT_100104,USR_1113,192.168.1.16,Toronto,Failed,Yes,14,20.0,4,3,Active,75,Critical
117,EVT_100117,USR_1160,10.0.0.148,Sydney,Failed,Yes,12,17.0,4,3,Locked,90,Critical
120,EVT_100120,USR_1031,198.51.100.42,London,Failed,Yes,9,105.0,116,2,Locked,85,Critical

In [39]:
df.to_csv(
    r"E:\python\project 2\cybersecurity_auth_risk_analytics.csv",
    index=False
)